[package]
name = "ruby_on_rust"
version = "0.0.0"
authors = ["Nami.WANG <namiheike@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.0.4"
lazy_static = "1.1.0"
maplit = "1.0.1"
strum = "0.10.0"
strum_macros = "0.10.0"
uuid = { version = "0.7", features = ["v4"] }
